// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="predict_model_predict_model,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcau20p-sfvb784-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.762800,HLS_SYN_LAT=194,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=11070,HLS_SYN_LUT=10288,HLS_VERSION=2025_1}" *)

module predict_model (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x,
        ap_return
);

parameter    ap_ST_fsm_state1 = 113'd1;
parameter    ap_ST_fsm_state2 = 113'd2;
parameter    ap_ST_fsm_state3 = 113'd4;
parameter    ap_ST_fsm_state4 = 113'd8;
parameter    ap_ST_fsm_state5 = 113'd16;
parameter    ap_ST_fsm_state6 = 113'd32;
parameter    ap_ST_fsm_state7 = 113'd64;
parameter    ap_ST_fsm_state8 = 113'd128;
parameter    ap_ST_fsm_state9 = 113'd256;
parameter    ap_ST_fsm_state10 = 113'd512;
parameter    ap_ST_fsm_state11 = 113'd1024;
parameter    ap_ST_fsm_state12 = 113'd2048;
parameter    ap_ST_fsm_state13 = 113'd4096;
parameter    ap_ST_fsm_state14 = 113'd8192;
parameter    ap_ST_fsm_state15 = 113'd16384;
parameter    ap_ST_fsm_state16 = 113'd32768;
parameter    ap_ST_fsm_state17 = 113'd65536;
parameter    ap_ST_fsm_state18 = 113'd131072;
parameter    ap_ST_fsm_state19 = 113'd262144;
parameter    ap_ST_fsm_state20 = 113'd524288;
parameter    ap_ST_fsm_state21 = 113'd1048576;
parameter    ap_ST_fsm_state22 = 113'd2097152;
parameter    ap_ST_fsm_state23 = 113'd4194304;
parameter    ap_ST_fsm_state24 = 113'd8388608;
parameter    ap_ST_fsm_state25 = 113'd16777216;
parameter    ap_ST_fsm_state26 = 113'd33554432;
parameter    ap_ST_fsm_state27 = 113'd67108864;
parameter    ap_ST_fsm_state28 = 113'd134217728;
parameter    ap_ST_fsm_state29 = 113'd268435456;
parameter    ap_ST_fsm_state30 = 113'd536870912;
parameter    ap_ST_fsm_state31 = 113'd1073741824;
parameter    ap_ST_fsm_state32 = 113'd2147483648;
parameter    ap_ST_fsm_state33 = 113'd4294967296;
parameter    ap_ST_fsm_state34 = 113'd8589934592;
parameter    ap_ST_fsm_state35 = 113'd17179869184;
parameter    ap_ST_fsm_state36 = 113'd34359738368;
parameter    ap_ST_fsm_state37 = 113'd68719476736;
parameter    ap_ST_fsm_state38 = 113'd137438953472;
parameter    ap_ST_fsm_state39 = 113'd274877906944;
parameter    ap_ST_fsm_state40 = 113'd549755813888;
parameter    ap_ST_fsm_state41 = 113'd1099511627776;
parameter    ap_ST_fsm_state42 = 113'd2199023255552;
parameter    ap_ST_fsm_state43 = 113'd4398046511104;
parameter    ap_ST_fsm_state44 = 113'd8796093022208;
parameter    ap_ST_fsm_state45 = 113'd17592186044416;
parameter    ap_ST_fsm_state46 = 113'd35184372088832;
parameter    ap_ST_fsm_state47 = 113'd70368744177664;
parameter    ap_ST_fsm_state48 = 113'd140737488355328;
parameter    ap_ST_fsm_state49 = 113'd281474976710656;
parameter    ap_ST_fsm_state50 = 113'd562949953421312;
parameter    ap_ST_fsm_state51 = 113'd1125899906842624;
parameter    ap_ST_fsm_state52 = 113'd2251799813685248;
parameter    ap_ST_fsm_state53 = 113'd4503599627370496;
parameter    ap_ST_fsm_state54 = 113'd9007199254740992;
parameter    ap_ST_fsm_state55 = 113'd18014398509481984;
parameter    ap_ST_fsm_state56 = 113'd36028797018963968;
parameter    ap_ST_fsm_state57 = 113'd72057594037927936;
parameter    ap_ST_fsm_state58 = 113'd144115188075855872;
parameter    ap_ST_fsm_state59 = 113'd288230376151711744;
parameter    ap_ST_fsm_state60 = 113'd576460752303423488;
parameter    ap_ST_fsm_state61 = 113'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 113'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 113'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 113'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 113'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 113'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 113'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 113'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 113'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 113'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 113'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 113'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 113'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 113'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 113'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 113'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 113'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 113'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 113'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 113'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 113'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 113'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 113'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 113'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 113'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 113'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 113'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 113'd154742504910672534362390528;
parameter    ap_ST_fsm_state89 = 113'd309485009821345068724781056;
parameter    ap_ST_fsm_state90 = 113'd618970019642690137449562112;
parameter    ap_ST_fsm_state91 = 113'd1237940039285380274899124224;
parameter    ap_ST_fsm_state92 = 113'd2475880078570760549798248448;
parameter    ap_ST_fsm_state93 = 113'd4951760157141521099596496896;
parameter    ap_ST_fsm_state94 = 113'd9903520314283042199192993792;
parameter    ap_ST_fsm_state95 = 113'd19807040628566084398385987584;
parameter    ap_ST_fsm_state96 = 113'd39614081257132168796771975168;
parameter    ap_ST_fsm_state97 = 113'd79228162514264337593543950336;
parameter    ap_ST_fsm_state98 = 113'd158456325028528675187087900672;
parameter    ap_ST_fsm_state99 = 113'd316912650057057350374175801344;
parameter    ap_ST_fsm_state100 = 113'd633825300114114700748351602688;
parameter    ap_ST_fsm_state101 = 113'd1267650600228229401496703205376;
parameter    ap_ST_fsm_state102 = 113'd2535301200456458802993406410752;
parameter    ap_ST_fsm_state103 = 113'd5070602400912917605986812821504;
parameter    ap_ST_fsm_state104 = 113'd10141204801825835211973625643008;
parameter    ap_ST_fsm_state105 = 113'd20282409603651670423947251286016;
parameter    ap_ST_fsm_state106 = 113'd40564819207303340847894502572032;
parameter    ap_ST_fsm_state107 = 113'd81129638414606681695789005144064;
parameter    ap_ST_fsm_state108 = 113'd162259276829213363391578010288128;
parameter    ap_ST_fsm_state109 = 113'd324518553658426726783156020576256;
parameter    ap_ST_fsm_state110 = 113'd649037107316853453566312041152512;
parameter    ap_ST_fsm_state111 = 113'd1298074214633706907132624082305024;
parameter    ap_ST_fsm_state112 = 113'd2596148429267413814265248164610048;
parameter    ap_ST_fsm_state113 = 113'd5192296858534827628530496329220096;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [511:0] x;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [112:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] grp_fu_270_p2;
reg   [63:0] reg_350;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state32;
wire    ap_CS_fsm_state40;
wire    ap_CS_fsm_state48;
wire    ap_CS_fsm_state56;
wire   [63:0] grp_fu_275_p2;
reg   [63:0] reg_356;
wire   [63:0] grp_fu_280_p2;
reg   [63:0] reg_362;
wire   [63:0] grp_fu_285_p2;
reg   [63:0] reg_368;
wire   [63:0] grp_fu_290_p2;
reg   [63:0] reg_374;
wire   [63:0] grp_fu_244_p2;
reg   [63:0] reg_380;
wire    ap_CS_fsm_state64;
wire    ap_CS_fsm_state85;
wire    ap_CS_fsm_state93;
wire    ap_CS_fsm_state101;
wire    ap_CS_fsm_state109;
wire   [63:0] grp_fu_248_p2;
reg   [63:0] reg_386;
wire   [63:0] grp_fu_252_p2;
reg   [63:0] reg_391;
wire   [63:0] grp_fu_256_p2;
reg   [63:0] reg_397;
wire   [63:0] grp_fu_260_p2;
reg   [63:0] reg_403;
wire   [63:0] bitcast_ln24_fu_413_p1;
wire   [63:0] bitcast_ln24_1_fu_432_p1;
reg   [63:0] trunc_ln24_2_reg_642;
reg   [63:0] trunc_ln24_3_reg_647;
reg   [63:0] trunc_ln24_4_reg_652;
reg   [63:0] trunc_ln24_5_reg_657;
reg   [63:0] trunc_ln24_6_reg_662;
reg   [63:0] trunc_ln24_7_reg_667;
wire   [63:0] grp_fu_295_p2;
reg   [63:0] mul17_reg_672;
wire   [63:0] grp_fu_300_p2;
reg   [63:0] mul24_reg_677;
wire   [63:0] grp_fu_305_p2;
reg   [63:0] mul25_reg_682;
wire   [63:0] grp_fu_310_p2;
reg   [63:0] mul32_reg_687;
wire   [63:0] grp_fu_315_p2;
reg   [63:0] mul33_reg_692;
wire   [63:0] bitcast_ln24_2_fu_501_p1;
wire    ap_CS_fsm_state9;
wire   [63:0] bitcast_ln24_3_fu_509_p1;
wire    ap_CS_fsm_state17;
wire   [63:0] bitcast_ln24_4_fu_517_p1;
wire    ap_CS_fsm_state25;
wire   [63:0] bitcast_ln24_5_fu_525_p1;
wire    ap_CS_fsm_state33;
wire   [63:0] bitcast_ln24_6_fu_533_p1;
wire    ap_CS_fsm_state41;
wire   [63:0] bitcast_ln24_7_fu_541_p1;
wire    ap_CS_fsm_state49;
wire    ap_CS_fsm_state72;
wire   [2:0] y_addr_2_reg_761;
wire    ap_CS_fsm_state73;
wire   [2:0] y_addr_3_reg_766;
wire    ap_CS_fsm_state74;
wire   [63:0] bitcast_ln36_fu_574_p1;
wire    ap_CS_fsm_state78;
wire   [63:0] bitcast_ln36_1_fu_579_p1;
wire   [63:0] bitcast_ln36_2_fu_584_p1;
wire    ap_CS_fsm_state86;
wire   [63:0] bitcast_ln36_3_fu_589_p1;
wire    ap_CS_fsm_state94;
wire   [63:0] bitcast_ln36_4_fu_594_p1;
wire    ap_CS_fsm_state102;
reg   [2:0] y_address0;
reg    y_ce0;
reg    y_we0;
reg   [63:0] y_d0;
wire   [63:0] y_q0;
reg   [2:0] y_address1;
reg    y_ce1;
wire   [63:0] y_q1;
wire    grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_ap_start;
wire    grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_ap_done;
wire    grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_ap_idle;
wire    grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_ap_ready;
wire   [2:0] grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_y_address0;
wire    grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_y_ce0;
wire    grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_y_we0;
wire   [63:0] grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_y_d0;
wire   [2:0] grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_y_address1;
wire    grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_y_ce1;
wire    grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_ap_start;
wire    grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_ap_done;
wire    grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_ap_idle;
wire    grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_ap_ready;
wire   [2:0] grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_y_address0;
wire    grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_y_ce0;
wire    grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_y_we0;
wire   [63:0] grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_y_d0;
wire   [2:0] grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_y_address1;
wire    grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_y_ce1;
wire    grp_predict_model_Pipeline_3_fu_238_ap_start;
wire    grp_predict_model_Pipeline_3_fu_238_ap_done;
wire    grp_predict_model_Pipeline_3_fu_238_ap_idle;
wire    grp_predict_model_Pipeline_3_fu_238_ap_ready;
wire   [2:0] grp_predict_model_Pipeline_3_fu_238_y_address0;
wire    grp_predict_model_Pipeline_3_fu_238_y_ce0;
wire   [2:0] grp_predict_model_Pipeline_3_fu_238_y_address1;
wire    grp_predict_model_Pipeline_3_fu_238_y_ce1;
wire   [34:0] grp_predict_model_Pipeline_3_fu_238_p_result_1_out;
wire    grp_predict_model_Pipeline_3_fu_238_p_result_1_out_ap_vld;
reg    grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_ap_start_reg;
wire    ap_CS_fsm_state75;
wire    ap_CS_fsm_state76;
wire    y_we0_out;
reg    grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_ap_start_reg;
wire    ap_CS_fsm_state110;
reg    grp_predict_model_Pipeline_3_fu_238_ap_start_reg;
reg   [112:0] ap_NS_fsm;
wire    ap_NS_fsm_state111;
wire    ap_CS_fsm_state112;
reg   [34:0] p_result_1_loc_fu_164;
wire    ap_CS_fsm_state113;
reg    y_we1_local;
reg   [63:0] y_d1_local;
wire   [63:0] bitcast_ln24_8_fu_549_p1;
reg    y_ce1_local;
reg   [2:0] y_address1_local;
reg    y_we0_local;
reg   [63:0] y_d0_local;
wire   [63:0] bitcast_ln25_fu_554_p1;
reg    y_ce0_local;
reg   [2:0] y_address0_local;
wire   [63:0] bitcast_ln26_fu_559_p1;
wire   [63:0] bitcast_ln27_fu_564_p1;
wire   [63:0] bitcast_ln28_fu_569_p1;
wire    ap_CS_fsm_state77;
reg   [63:0] grp_fu_244_p0;
reg   [63:0] grp_fu_244_p1;
wire    ap_CS_fsm_state57;
wire    ap_CS_fsm_state65;
wire    ap_CS_fsm_state66;
wire    ap_CS_fsm_state67;
reg   [63:0] grp_fu_248_p0;
reg   [63:0] grp_fu_248_p1;
reg   [63:0] grp_fu_252_p0;
reg   [63:0] grp_fu_252_p1;
reg   [63:0] grp_fu_256_p0;
reg   [63:0] grp_fu_256_p1;
reg   [63:0] grp_fu_260_p0;
reg   [63:0] grp_fu_260_p1;
reg   [63:0] grp_fu_270_p0;
reg   [63:0] grp_fu_270_p1;
reg   [63:0] grp_fu_275_p0;
reg   [63:0] grp_fu_275_p1;
reg   [63:0] grp_fu_280_p0;
reg   [63:0] grp_fu_280_p1;
reg   [63:0] grp_fu_285_p0;
reg   [63:0] grp_fu_285_p1;
reg   [63:0] grp_fu_290_p0;
reg   [63:0] grp_fu_290_p1;
wire   [63:0] trunc_ln24_fu_409_p1;
wire   [63:0] trunc_ln24_1_fu_422_p4;
wire   [31:0] trunc_ln1_fu_602_p4;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
wire    ap_ST_fsm_state74_blk;
wire    ap_ST_fsm_state75_blk;
reg    ap_ST_fsm_state76_blk;
wire    ap_ST_fsm_state77_blk;
wire    ap_ST_fsm_state78_blk;
wire    ap_ST_fsm_state79_blk;
wire    ap_ST_fsm_state80_blk;
wire    ap_ST_fsm_state81_blk;
wire    ap_ST_fsm_state82_blk;
wire    ap_ST_fsm_state83_blk;
wire    ap_ST_fsm_state84_blk;
wire    ap_ST_fsm_state85_blk;
wire    ap_ST_fsm_state86_blk;
wire    ap_ST_fsm_state87_blk;
wire    ap_ST_fsm_state88_blk;
wire    ap_ST_fsm_state89_blk;
wire    ap_ST_fsm_state90_blk;
wire    ap_ST_fsm_state91_blk;
wire    ap_ST_fsm_state92_blk;
wire    ap_ST_fsm_state93_blk;
wire    ap_ST_fsm_state94_blk;
wire    ap_ST_fsm_state95_blk;
wire    ap_ST_fsm_state96_blk;
wire    ap_ST_fsm_state97_blk;
wire    ap_ST_fsm_state98_blk;
wire    ap_ST_fsm_state99_blk;
wire    ap_ST_fsm_state100_blk;
wire    ap_ST_fsm_state101_blk;
wire    ap_ST_fsm_state102_blk;
wire    ap_ST_fsm_state103_blk;
wire    ap_ST_fsm_state104_blk;
wire    ap_ST_fsm_state105_blk;
wire    ap_ST_fsm_state106_blk;
wire    ap_ST_fsm_state107_blk;
wire    ap_ST_fsm_state108_blk;
wire    ap_ST_fsm_state109_blk;
reg    ap_ST_fsm_state110_blk;
wire    ap_ST_fsm_state111_blk;
reg    ap_ST_fsm_state112_blk;
wire    ap_ST_fsm_state113_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 113'd1;
#0 grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_ap_start_reg = 1'b0;
#0 grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_ap_start_reg = 1'b0;
#0 grp_predict_model_Pipeline_3_fu_238_ap_start_reg = 1'b0;
end

predict_model_y_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
y_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(y_address0),
    .ce0(y_ce0),
    .we0(y_we0),
    .d0(y_d0),
    .q0(y_q0),
    .address1(y_address1),
    .ce1(y_ce1),
    .we1(y_we1_local),
    .d1(y_d1_local),
    .q1(y_q1)
);

predict_model_predict_model_Pipeline_VITIS_LOOP_31_1 grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_ap_start),
    .ap_done(grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_ap_done),
    .ap_idle(grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_ap_idle),
    .ap_ready(grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_ap_ready),
    .y_address0(grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_y_address0),
    .y_ce0(grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_y_ce0),
    .y_we0(grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_y_we0),
    .y_d0(grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_y_d0),
    .y_address1(grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_y_address1),
    .y_ce1(grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_y_ce1),
    .y_q1(y_q1)
);

predict_model_predict_model_Pipeline_VITIS_LOOP_38_2 grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_ap_start),
    .ap_done(grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_ap_done),
    .ap_idle(grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_ap_idle),
    .ap_ready(grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_ap_ready),
    .y_address0(grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_y_address0),
    .y_ce0(grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_y_ce0),
    .y_we0(grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_y_we0),
    .y_d0(grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_y_d0),
    .y_address1(grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_y_address1),
    .y_ce1(grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_y_ce1),
    .y_q1(y_q1),
    .Z(reg_380)
);

predict_model_predict_model_Pipeline_3 grp_predict_model_Pipeline_3_fu_238(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_predict_model_Pipeline_3_fu_238_ap_start),
    .ap_done(grp_predict_model_Pipeline_3_fu_238_ap_done),
    .ap_idle(grp_predict_model_Pipeline_3_fu_238_ap_idle),
    .ap_ready(grp_predict_model_Pipeline_3_fu_238_ap_ready),
    .y_address0(grp_predict_model_Pipeline_3_fu_238_y_address0),
    .y_ce0(grp_predict_model_Pipeline_3_fu_238_y_ce0),
    .y_q0(y_q0),
    .y_address1(grp_predict_model_Pipeline_3_fu_238_y_address1),
    .y_ce1(grp_predict_model_Pipeline_3_fu_238_y_ce1),
    .y_q1(y_q1),
    .p_result_1_out(grp_predict_model_Pipeline_3_fu_238_p_result_1_out),
    .p_result_1_out_ap_vld(grp_predict_model_Pipeline_3_fu_238_p_result_1_out_ap_vld)
);

predict_model_dadd_64ns_64ns_64_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_8_full_dsp_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_244_p0),
    .din1(grp_fu_244_p1),
    .ce(1'b1),
    .dout(grp_fu_244_p2)
);

predict_model_dadd_64ns_64ns_64_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_8_full_dsp_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_248_p0),
    .din1(grp_fu_248_p1),
    .ce(1'b1),
    .dout(grp_fu_248_p2)
);

predict_model_dadd_64ns_64ns_64_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_8_full_dsp_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_252_p0),
    .din1(grp_fu_252_p1),
    .ce(1'b1),
    .dout(grp_fu_252_p2)
);

predict_model_dadd_64ns_64ns_64_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_8_full_dsp_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_256_p0),
    .din1(grp_fu_256_p1),
    .ce(1'b1),
    .dout(grp_fu_256_p2)
);

predict_model_dadd_64ns_64ns_64_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_8_full_dsp_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_260_p0),
    .din1(grp_fu_260_p1),
    .ce(1'b1),
    .dout(grp_fu_260_p2)
);

predict_model_dmul_64ns_64ns_64_8_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_8_max_dsp_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_270_p0),
    .din1(grp_fu_270_p1),
    .ce(1'b1),
    .dout(grp_fu_270_p2)
);

predict_model_dmul_64ns_64ns_64_8_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_8_max_dsp_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_275_p0),
    .din1(grp_fu_275_p1),
    .ce(1'b1),
    .dout(grp_fu_275_p2)
);

predict_model_dmul_64ns_64ns_64_8_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_8_max_dsp_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_280_p0),
    .din1(grp_fu_280_p1),
    .ce(1'b1),
    .dout(grp_fu_280_p2)
);

predict_model_dmul_64ns_64ns_64_8_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_8_max_dsp_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_285_p0),
    .din1(grp_fu_285_p1),
    .ce(1'b1),
    .dout(grp_fu_285_p2)
);

predict_model_dmul_64ns_64ns_64_8_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_8_max_dsp_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_290_p0),
    .din1(grp_fu_290_p1),
    .ce(1'b1),
    .dout(grp_fu_290_p2)
);

predict_model_dmul_64ns_64ns_64_8_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_8_max_dsp_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln24_1_fu_432_p1),
    .din1(64'd13822224159241491432),
    .ce(1'b1),
    .dout(grp_fu_295_p2)
);

predict_model_dmul_64ns_64ns_64_8_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_8_max_dsp_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln24_fu_413_p1),
    .din1(64'd13820377070184144266),
    .ce(1'b1),
    .dout(grp_fu_300_p2)
);

predict_model_dmul_64ns_64ns_64_8_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_8_max_dsp_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln24_1_fu_432_p1),
    .din1(64'd4600088729059022329),
    .ce(1'b1),
    .dout(grp_fu_305_p2)
);

predict_model_dmul_64ns_64ns_64_8_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_8_max_dsp_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln24_fu_413_p1),
    .din1(64'd4594997484259889812),
    .ce(1'b1),
    .dout(grp_fu_310_p2)
);

predict_model_dmul_64ns_64ns_64_8_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_8_max_dsp_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln24_1_fu_432_p1),
    .din1(64'd4586012053445780972),
    .ce(1'b1),
    .dout(grp_fu_315_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_predict_model_Pipeline_3_fu_238_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state111) & (1'b1 == ap_CS_fsm_state110))) begin
            grp_predict_model_Pipeline_3_fu_238_ap_start_reg <= 1'b1;
        end else if ((grp_predict_model_Pipeline_3_fu_238_ap_ready == 1'b1)) begin
            grp_predict_model_Pipeline_3_fu_238_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state75)) begin
            grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_ap_start_reg <= 1'b1;
        end else if ((grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_ap_ready == 1'b1)) begin
            grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state109)) begin
            grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_ap_start_reg <= 1'b1;
        end else if ((grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_ap_ready == 1'b1)) begin
            grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        mul17_reg_672 <= grp_fu_295_p2;
        mul24_reg_677 <= grp_fu_300_p2;
        mul25_reg_682 <= grp_fu_305_p2;
        mul32_reg_687 <= grp_fu_310_p2;
        mul33_reg_692 <= grp_fu_315_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_predict_model_Pipeline_3_fu_238_p_result_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state112))) begin
        p_result_1_loc_fu_164 <= grp_predict_model_Pipeline_3_fu_238_p_result_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state8))) begin
        reg_350 <= grp_fu_270_p2;
        reg_356 <= grp_fu_275_p2;
        reg_362 <= grp_fu_280_p2;
        reg_368 <= grp_fu_285_p2;
        reg_374 <= grp_fu_290_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state109) | (1'b1 == ap_CS_fsm_state101) | (1'b1 == ap_CS_fsm_state93) | (1'b1 == ap_CS_fsm_state85) | (1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state16))) begin
        reg_380 <= grp_fu_244_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state16))) begin
        reg_386 <= grp_fu_248_p2;
        reg_391 <= grp_fu_252_p2;
        reg_397 <= grp_fu_256_p2;
        reg_403 <= grp_fu_260_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln24_2_reg_642 <= {{x[191:128]}};
        trunc_ln24_3_reg_647 <= {{x[255:192]}};
        trunc_ln24_4_reg_652 <= {{x[319:256]}};
        trunc_ln24_5_reg_657 <= {{x[383:320]}};
        trunc_ln24_6_reg_662 <= {{x[447:384]}};
        trunc_ln24_7_reg_667 <= {{x[511:448]}};
    end
end

assign ap_ST_fsm_state100_blk = 1'b0;

assign ap_ST_fsm_state101_blk = 1'b0;

assign ap_ST_fsm_state102_blk = 1'b0;

assign ap_ST_fsm_state103_blk = 1'b0;

assign ap_ST_fsm_state104_blk = 1'b0;

assign ap_ST_fsm_state105_blk = 1'b0;

assign ap_ST_fsm_state106_blk = 1'b0;

assign ap_ST_fsm_state107_blk = 1'b0;

assign ap_ST_fsm_state108_blk = 1'b0;

assign ap_ST_fsm_state109_blk = 1'b0;

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_ap_done == 1'b0)) begin
        ap_ST_fsm_state110_blk = 1'b1;
    end else begin
        ap_ST_fsm_state110_blk = 1'b0;
    end
end

assign ap_ST_fsm_state111_blk = 1'b0;

always @ (*) begin
    if ((grp_predict_model_Pipeline_3_fu_238_ap_done == 1'b0)) begin
        ap_ST_fsm_state112_blk = 1'b1;
    end else begin
        ap_ST_fsm_state112_blk = 1'b0;
    end
end

assign ap_ST_fsm_state113_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

assign ap_ST_fsm_state74_blk = 1'b0;

assign ap_ST_fsm_state75_blk = 1'b0;

always @ (*) begin
    if ((grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_ap_done == 1'b0)) begin
        ap_ST_fsm_state76_blk = 1'b1;
    end else begin
        ap_ST_fsm_state76_blk = 1'b0;
    end
end

assign ap_ST_fsm_state77_blk = 1'b0;

assign ap_ST_fsm_state78_blk = 1'b0;

assign ap_ST_fsm_state79_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state80_blk = 1'b0;

assign ap_ST_fsm_state81_blk = 1'b0;

assign ap_ST_fsm_state82_blk = 1'b0;

assign ap_ST_fsm_state83_blk = 1'b0;

assign ap_ST_fsm_state84_blk = 1'b0;

assign ap_ST_fsm_state85_blk = 1'b0;

assign ap_ST_fsm_state86_blk = 1'b0;

assign ap_ST_fsm_state87_blk = 1'b0;

assign ap_ST_fsm_state88_blk = 1'b0;

assign ap_ST_fsm_state89_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state90_blk = 1'b0;

assign ap_ST_fsm_state91_blk = 1'b0;

assign ap_ST_fsm_state92_blk = 1'b0;

assign ap_ST_fsm_state93_blk = 1'b0;

assign ap_ST_fsm_state94_blk = 1'b0;

assign ap_ST_fsm_state95_blk = 1'b0;

assign ap_ST_fsm_state96_blk = 1'b0;

assign ap_ST_fsm_state97_blk = 1'b0;

assign ap_ST_fsm_state98_blk = 1'b0;

assign ap_ST_fsm_state99_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state113)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state113)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        grp_fu_244_p0 = bitcast_ln36_fu_574_p1;
    end else if ((1'b1 == ap_CS_fsm_state67)) begin
        grp_fu_244_p0 = reg_403;
    end else if ((1'b1 == ap_CS_fsm_state66)) begin
        grp_fu_244_p0 = reg_391;
    end else if (((1'b1 == ap_CS_fsm_state65) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state102) | (1'b1 == ap_CS_fsm_state94) | (1'b1 == ap_CS_fsm_state86) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state17))) begin
        grp_fu_244_p0 = reg_380;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_244_p0 = reg_350;
    end else begin
        grp_fu_244_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state102)) begin
        grp_fu_244_p1 = bitcast_ln36_4_fu_594_p1;
    end else if ((1'b1 == ap_CS_fsm_state94)) begin
        grp_fu_244_p1 = bitcast_ln36_3_fu_589_p1;
    end else if ((1'b1 == ap_CS_fsm_state86)) begin
        grp_fu_244_p1 = bitcast_ln36_2_fu_584_p1;
    end else if ((1'b1 == ap_CS_fsm_state78)) begin
        grp_fu_244_p1 = bitcast_ln36_1_fu_579_p1;
    end else if ((1'b1 == ap_CS_fsm_state67)) begin
        grp_fu_244_p1 = 64'd4636515358939365996;
    end else if ((1'b1 == ap_CS_fsm_state66)) begin
        grp_fu_244_p1 = 64'd13848281446286152934;
    end else if ((1'b1 == ap_CS_fsm_state65)) begin
        grp_fu_244_p1 = 64'd13866966288586204947;
    end else if (((1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state17))) begin
        grp_fu_244_p1 = reg_350;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_244_p1 = reg_356;
    end else begin
        grp_fu_244_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state66)) begin
        grp_fu_248_p0 = reg_397;
    end else if (((1'b1 == ap_CS_fsm_state65) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state17))) begin
        grp_fu_248_p0 = reg_386;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_248_p0 = reg_362;
    end else begin
        grp_fu_248_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state66)) begin
        grp_fu_248_p1 = 64'd4629727756063740588;
    end else if ((1'b1 == ap_CS_fsm_state65)) begin
        grp_fu_248_p1 = 64'd4639982068915107220;
    end else if (((1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state17))) begin
        grp_fu_248_p1 = reg_356;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_248_p1 = reg_368;
    end else begin
        grp_fu_248_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state17))) begin
        grp_fu_252_p0 = reg_391;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_252_p0 = reg_374;
    end else begin
        grp_fu_252_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state17))) begin
        grp_fu_252_p1 = reg_362;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_252_p1 = mul17_reg_672;
    end else begin
        grp_fu_252_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state17))) begin
        grp_fu_256_p0 = reg_397;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_256_p0 = mul24_reg_677;
    end else begin
        grp_fu_256_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state17))) begin
        grp_fu_256_p1 = reg_368;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_256_p1 = mul25_reg_682;
    end else begin
        grp_fu_256_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state17))) begin
        grp_fu_260_p0 = reg_403;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_260_p0 = mul32_reg_687;
    end else begin
        grp_fu_260_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state17))) begin
        grp_fu_260_p1 = reg_374;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_260_p1 = mul33_reg_692;
    end else begin
        grp_fu_260_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_270_p0 = bitcast_ln24_7_fu_541_p1;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        grp_fu_270_p0 = bitcast_ln24_6_fu_533_p1;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        grp_fu_270_p0 = bitcast_ln24_5_fu_525_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_270_p0 = bitcast_ln24_4_fu_517_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_270_p0 = bitcast_ln24_3_fu_509_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_270_p0 = bitcast_ln24_2_fu_501_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_270_p0 = bitcast_ln24_fu_413_p1;
    end else begin
        grp_fu_270_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_270_p1 = 64'd4542355007950183762;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        grp_fu_270_p1 = 64'd4597251986089236295;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        grp_fu_270_p1 = 64'd4607694955459209935;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_270_p1 = 64'd4611796252495035096;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_270_p1 = 64'd4597171764766110637;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_270_p1 = 64'd13811595471093014152;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_270_p1 = 64'd13817251042131202586;
    end else begin
        grp_fu_270_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_275_p0 = bitcast_ln24_7_fu_541_p1;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        grp_fu_275_p0 = bitcast_ln24_6_fu_533_p1;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        grp_fu_275_p0 = bitcast_ln24_5_fu_525_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_275_p0 = bitcast_ln24_4_fu_517_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_275_p0 = bitcast_ln24_3_fu_509_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_275_p0 = bitcast_ln24_2_fu_501_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_275_p0 = bitcast_ln24_1_fu_432_p1;
    end else begin
        grp_fu_275_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_275_p1 = 64'd13774410371253584510;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        grp_fu_275_p1 = 64'd13811085596673690951;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        grp_fu_275_p1 = 64'd13828213226296054602;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_275_p1 = 64'd4608090979807694733;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_275_p1 = 64'd4595267706794773100;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_275_p1 = 64'd13823960089876375087;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_275_p1 = 64'd4597328992562803950;
    end else begin
        grp_fu_275_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_280_p0 = bitcast_ln24_7_fu_541_p1;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        grp_fu_280_p0 = bitcast_ln24_6_fu_533_p1;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        grp_fu_280_p0 = bitcast_ln24_5_fu_525_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_280_p0 = bitcast_ln24_4_fu_517_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_280_p0 = bitcast_ln24_3_fu_509_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_280_p0 = bitcast_ln24_2_fu_501_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_280_p0 = bitcast_ln24_fu_413_p1;
    end else begin
        grp_fu_280_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_280_p1 = 64'd4545352294071230939;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        grp_fu_280_p1 = 64'd13807542583040616573;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        grp_fu_280_p1 = 64'd13813402737535427776;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_280_p1 = 64'd4593570899542341961;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_280_p1 = 64'd4595866818059128811;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_280_p1 = 64'd4603226689759464696;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_280_p1 = 64'd13824470681088614981;
    end else begin
        grp_fu_280_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_285_p0 = bitcast_ln24_7_fu_541_p1;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        grp_fu_285_p0 = bitcast_ln24_6_fu_533_p1;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        grp_fu_285_p0 = bitcast_ln24_5_fu_525_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_285_p0 = bitcast_ln24_4_fu_517_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_285_p0 = bitcast_ln24_3_fu_509_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_285_p0 = bitcast_ln24_2_fu_501_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_285_p0 = bitcast_ln24_1_fu_432_p1;
    end else begin
        grp_fu_285_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_285_p1 = 64'd4538319676825574256;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        grp_fu_285_p1 = 64'd13813799934795995208;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        grp_fu_285_p1 = 64'd13801531139433370768;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_285_p1 = 64'd13840468210982211422;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_285_p1 = 64'd13822313533662485359;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_285_p1 = 64'd13806333141663328122;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_285_p1 = 64'd13823092153958431627;
    end else begin
        grp_fu_285_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_290_p0 = bitcast_ln24_7_fu_541_p1;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        grp_fu_290_p0 = bitcast_ln24_6_fu_533_p1;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        grp_fu_290_p0 = bitcast_ln24_5_fu_525_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_290_p0 = bitcast_ln24_4_fu_517_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_290_p0 = bitcast_ln24_3_fu_509_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_290_p0 = bitcast_ln24_2_fu_501_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_290_p0 = bitcast_ln24_fu_413_p1;
    end else begin
        grp_fu_290_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_290_p1 = 64'd13769103004891452513;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        grp_fu_290_p1 = 64'd13812532343120462133;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        grp_fu_290_p1 = 64'd13822215770908883086;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_290_p1 = 64'd4609122958945748396;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_290_p1 = 64'd13822174894185023641;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_290_p1 = 64'd13814925208904250891;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_290_p1 = 64'd4603568365379215129;
    end else begin
        grp_fu_290_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state112)) begin
        y_address0 = grp_predict_model_Pipeline_3_fu_238_y_address0;
    end else if ((1'b1 == ap_CS_fsm_state110)) begin
        y_address0 = grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_y_address0;
    end else if ((1'b1 == ap_CS_fsm_state76)) begin
        y_address0 = grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_y_address0;
    end else begin
        y_address0 = y_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state93)) begin
        y_address0_local = y_addr_3_reg_766;
    end else if ((1'b1 == ap_CS_fsm_state77)) begin
        y_address0_local = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state74)) begin
        y_address0_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state73)) begin
        y_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state72)) begin
        y_address0_local = 64'd1;
    end else begin
        y_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state112)) begin
        y_address1 = grp_predict_model_Pipeline_3_fu_238_y_address1;
    end else if ((1'b1 == ap_CS_fsm_state110)) begin
        y_address1 = grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_y_address1;
    end else if ((1'b1 == ap_CS_fsm_state76)) begin
        y_address1 = grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_y_address1;
    end else begin
        y_address1 = y_address1_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state101)) begin
        y_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state85)) begin
        y_address1_local = y_addr_2_reg_761;
    end else if ((1'b1 == ap_CS_fsm_state77)) begin
        y_address1_local = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state73)) begin
        y_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state72)) begin
        y_address1_local = 64'd0;
    end else begin
        y_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state112)) begin
        y_ce0 = grp_predict_model_Pipeline_3_fu_238_y_ce0;
    end else if ((1'b1 == ap_CS_fsm_state110)) begin
        y_ce0 = grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_y_ce0;
    end else if ((1'b1 == ap_CS_fsm_state76)) begin
        y_ce0 = grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_y_ce0;
    end else begin
        y_ce0 = y_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73) | (1'b1 == ap_CS_fsm_state72) | (1'b1 == ap_CS_fsm_state93))) begin
        y_ce0_local = 1'b1;
    end else begin
        y_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state112)) begin
        y_ce1 = grp_predict_model_Pipeline_3_fu_238_y_ce1;
    end else if ((1'b1 == ap_CS_fsm_state110)) begin
        y_ce1 = grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_y_ce1;
    end else if ((1'b1 == ap_CS_fsm_state76)) begin
        y_ce1 = grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_y_ce1;
    end else begin
        y_ce1 = y_ce1_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state73) | (1'b1 == ap_CS_fsm_state72) | (1'b1 == ap_CS_fsm_state101) | (1'b1 == ap_CS_fsm_state85))) begin
        y_ce1_local = 1'b1;
    end else begin
        y_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state110)) begin
        y_d0 = grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_y_d0;
    end else if ((1'b1 == ap_CS_fsm_state76)) begin
        y_d0 = grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_y_d0;
    end else begin
        y_d0 = y_d0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state74)) begin
        y_d0_local = bitcast_ln28_fu_569_p1;
    end else if ((1'b1 == ap_CS_fsm_state73)) begin
        y_d0_local = bitcast_ln27_fu_564_p1;
    end else if ((1'b1 == ap_CS_fsm_state72)) begin
        y_d0_local = bitcast_ln25_fu_554_p1;
    end else begin
        y_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state73)) begin
        y_d1_local = bitcast_ln26_fu_559_p1;
    end else if ((1'b1 == ap_CS_fsm_state72)) begin
        y_d1_local = bitcast_ln24_8_fu_549_p1;
    end else begin
        y_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state110)) begin
        y_we0 = grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_y_we0;
    end else if ((1'b1 == ap_CS_fsm_state76)) begin
        y_we0 = grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_y_we0;
    end else begin
        y_we0 = (y_we0_out | 1'b0);
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73) | (1'b1 == ap_CS_fsm_state72))) begin
        y_we0_local = 1'b1;
    end else begin
        y_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state73) | (1'b1 == ap_CS_fsm_state72))) begin
        y_we1_local = 1'b1;
    end else begin
        y_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            if (((grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state76))) begin
                ap_NS_fsm = ap_ST_fsm_state77;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state76;
            end
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            ap_NS_fsm = ap_ST_fsm_state89;
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state90;
        end
        ap_ST_fsm_state90 : begin
            ap_NS_fsm = ap_ST_fsm_state91;
        end
        ap_ST_fsm_state91 : begin
            ap_NS_fsm = ap_ST_fsm_state92;
        end
        ap_ST_fsm_state92 : begin
            ap_NS_fsm = ap_ST_fsm_state93;
        end
        ap_ST_fsm_state93 : begin
            ap_NS_fsm = ap_ST_fsm_state94;
        end
        ap_ST_fsm_state94 : begin
            ap_NS_fsm = ap_ST_fsm_state95;
        end
        ap_ST_fsm_state95 : begin
            ap_NS_fsm = ap_ST_fsm_state96;
        end
        ap_ST_fsm_state96 : begin
            ap_NS_fsm = ap_ST_fsm_state97;
        end
        ap_ST_fsm_state97 : begin
            ap_NS_fsm = ap_ST_fsm_state98;
        end
        ap_ST_fsm_state98 : begin
            ap_NS_fsm = ap_ST_fsm_state99;
        end
        ap_ST_fsm_state99 : begin
            ap_NS_fsm = ap_ST_fsm_state100;
        end
        ap_ST_fsm_state100 : begin
            ap_NS_fsm = ap_ST_fsm_state101;
        end
        ap_ST_fsm_state101 : begin
            ap_NS_fsm = ap_ST_fsm_state102;
        end
        ap_ST_fsm_state102 : begin
            ap_NS_fsm = ap_ST_fsm_state103;
        end
        ap_ST_fsm_state103 : begin
            ap_NS_fsm = ap_ST_fsm_state104;
        end
        ap_ST_fsm_state104 : begin
            ap_NS_fsm = ap_ST_fsm_state105;
        end
        ap_ST_fsm_state105 : begin
            ap_NS_fsm = ap_ST_fsm_state106;
        end
        ap_ST_fsm_state106 : begin
            ap_NS_fsm = ap_ST_fsm_state107;
        end
        ap_ST_fsm_state107 : begin
            ap_NS_fsm = ap_ST_fsm_state108;
        end
        ap_ST_fsm_state108 : begin
            ap_NS_fsm = ap_ST_fsm_state109;
        end
        ap_ST_fsm_state109 : begin
            ap_NS_fsm = ap_ST_fsm_state110;
        end
        ap_ST_fsm_state110 : begin
            if (((grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state110))) begin
                ap_NS_fsm = ap_ST_fsm_state111;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state110;
            end
        end
        ap_ST_fsm_state111 : begin
            ap_NS_fsm = ap_ST_fsm_state112;
        end
        ap_ST_fsm_state112 : begin
            if (((grp_predict_model_Pipeline_3_fu_238_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state112))) begin
                ap_NS_fsm = ap_ST_fsm_state113;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state112;
            end
        end
        ap_ST_fsm_state113 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state101 = ap_CS_fsm[32'd100];

assign ap_CS_fsm_state102 = ap_CS_fsm[32'd101];

assign ap_CS_fsm_state109 = ap_CS_fsm[32'd108];

assign ap_CS_fsm_state110 = ap_CS_fsm[32'd109];

assign ap_CS_fsm_state112 = ap_CS_fsm[32'd111];

assign ap_CS_fsm_state113 = ap_CS_fsm[32'd112];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state64 = ap_CS_fsm[32'd63];

assign ap_CS_fsm_state65 = ap_CS_fsm[32'd64];

assign ap_CS_fsm_state66 = ap_CS_fsm[32'd65];

assign ap_CS_fsm_state67 = ap_CS_fsm[32'd66];

assign ap_CS_fsm_state72 = ap_CS_fsm[32'd71];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

assign ap_CS_fsm_state75 = ap_CS_fsm[32'd74];

assign ap_CS_fsm_state76 = ap_CS_fsm[32'd75];

assign ap_CS_fsm_state77 = ap_CS_fsm[32'd76];

assign ap_CS_fsm_state78 = ap_CS_fsm[32'd77];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state85 = ap_CS_fsm[32'd84];

assign ap_CS_fsm_state86 = ap_CS_fsm[32'd85];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state93 = ap_CS_fsm[32'd92];

assign ap_CS_fsm_state94 = ap_CS_fsm[32'd93];

assign ap_NS_fsm_state111 = ap_NS_fsm[32'd110];

assign ap_return = (trunc_ln1_fu_602_p4 + 32'd1);

assign bitcast_ln24_1_fu_432_p1 = trunc_ln24_1_fu_422_p4;

assign bitcast_ln24_2_fu_501_p1 = trunc_ln24_2_reg_642;

assign bitcast_ln24_3_fu_509_p1 = trunc_ln24_3_reg_647;

assign bitcast_ln24_4_fu_517_p1 = trunc_ln24_4_reg_652;

assign bitcast_ln24_5_fu_525_p1 = trunc_ln24_5_reg_657;

assign bitcast_ln24_6_fu_533_p1 = trunc_ln24_6_reg_662;

assign bitcast_ln24_7_fu_541_p1 = trunc_ln24_7_reg_667;

assign bitcast_ln24_8_fu_549_p1 = grp_fu_244_p2;

assign bitcast_ln24_fu_413_p1 = trunc_ln24_fu_409_p1;

assign bitcast_ln25_fu_554_p1 = grp_fu_248_p2;

assign bitcast_ln26_fu_559_p1 = grp_fu_244_p2;

assign bitcast_ln27_fu_564_p1 = grp_fu_248_p2;

assign bitcast_ln28_fu_569_p1 = grp_fu_244_p2;

assign bitcast_ln36_1_fu_579_p1 = y_q1;

assign bitcast_ln36_2_fu_584_p1 = y_q1;

assign bitcast_ln36_3_fu_589_p1 = y_q0;

assign bitcast_ln36_4_fu_594_p1 = y_q1;

assign bitcast_ln36_fu_574_p1 = y_q0;

assign grp_predict_model_Pipeline_3_fu_238_ap_start = grp_predict_model_Pipeline_3_fu_238_ap_start_reg;

assign grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_ap_start = grp_predict_model_Pipeline_VITIS_LOOP_31_1_fu_227_ap_start_reg;

assign grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_ap_start = grp_predict_model_Pipeline_VITIS_LOOP_38_2_fu_232_ap_start_reg;

assign trunc_ln1_fu_602_p4 = {{p_result_1_loc_fu_164[34:3]}};

assign trunc_ln24_1_fu_422_p4 = {{x[127:64]}};

assign trunc_ln24_fu_409_p1 = x[63:0];

assign y_addr_2_reg_761 = 64'd2;

assign y_addr_3_reg_766 = 64'd3;

assign y_we0_out = y_we0_local;

endmodule //predict_model
