// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module predict_model_predict_model_Pipeline_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y_address0,
        y_ce0,
        y_q0,
        y_address1,
        y_ce1,
        y_q1,
        p_result_1_out,
        p_result_1_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] y_address0;
output   y_ce0;
input  [63:0] y_q0;
output  [2:0] y_address1;
output   y_ce1;
input  [63:0] y_q1;
output  [34:0] p_result_1_out;
output   p_result_1_out_ap_vld;

reg ap_idle;
reg p_result_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [0:0] icmp_ln5658_fu_111_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_subdone;
reg   [63:0] p_result_2_reg_267;
wire    ap_block_pp0_stage1_11001;
wire   [2:0] add_ln5658_fu_117_p2;
reg   [2:0] add_ln5658_reg_275;
wire    ap_block_pp0_stage2_11001;
wire   [0:0] icmp_ln43_fu_186_p2;
reg   [0:0] icmp_ln43_reg_300;
wire   [0:0] icmp_ln43_1_fu_192_p2;
reg   [0:0] icmp_ln43_1_reg_305;
wire   [0:0] icmp_ln43_2_fu_198_p2;
reg   [0:0] icmp_ln43_2_reg_310;
wire   [0:0] icmp_ln43_3_fu_204_p2;
reg   [0:0] icmp_ln43_3_reg_315;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln43_fu_138_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln5658_fu_123_p1;
reg   [2:0] idx_fu_46;
wire    ap_loop_init;
wire    ap_block_pp0_stage0_11001;
reg   [63:0] p_result_1_fu_50;
wire   [63:0] p_result_fu_241_p3;
wire    ap_block_pp0_stage1_01001;
reg    y_ce1_local;
reg    y_ce0_local;
wire   [63:0] grp_fu_86_p0;
wire   [63:0] grp_fu_86_p1;
wire    ap_block_pp0_stage2;
wire   [2:0] lshr_ln_fu_128_p4;
wire   [10:0] tmp_1_fu_158_p4;
wire   [51:0] trunc_ln43_fu_168_p1;
wire   [10:0] tmp_2_fu_172_p4;
wire   [51:0] trunc_ln43_1_fu_182_p1;
wire    ap_block_pp0_stage0;
wire   [5:0] p_first_assign_fu_210_p3;
wire   [0:0] or_ln43_1_fu_225_p2;
wire   [0:0] grp_fu_86_p2;
wire   [0:0] and_ln43_fu_229_p2;
wire   [0:0] or_ln43_fu_221_p2;
wire   [0:0] and_ln43_1_fu_235_p2;
wire   [63:0] zext_ln5653_fu_217_p1;
wire    ap_block_pp0_stage2_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 idx_fu_46 = 3'd0;
#0 p_result_1_fu_50 = 64'd0;
#0 ap_done_reg = 1'b0;
end

predict_model_dcmp_64ns_64ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_2_no_dsp_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_86_p0),
    .din1(grp_fu_86_p1),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_86_p2)
);

predict_model_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        idx_fu_46 <= 3'd0;
    end else if (((icmp_ln5658_fu_111_p2 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        idx_fu_46 <= add_ln5658_fu_117_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_result_1_fu_50 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            p_result_1_fu_50 <= p_result_fu_241_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln5658_reg_275 <= add_ln5658_fu_117_p2;
        p_result_2_reg_267 <= p_result_1_fu_50;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        icmp_ln43_1_reg_305 <= icmp_ln43_1_fu_192_p2;
        icmp_ln43_2_reg_310 <= icmp_ln43_2_fu_198_p2;
        icmp_ln43_3_reg_315 <= icmp_ln43_3_fu_204_p2;
        icmp_ln43_reg_300 <= icmp_ln43_fu_186_p2;
    end
end

always @ (*) begin
    if (((icmp_ln5658_fu_111_p2 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln5658_fu_111_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_result_1_out_ap_vld = 1'b1;
    end else begin
        p_result_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        y_ce0_local = 1'b1;
    end else begin
        y_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        y_ce1_local = 1'b1;
    end else begin
        y_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln5658_fu_117_p2 = (idx_fu_46 + 3'd1);

assign and_ln43_1_fu_235_p2 = (or_ln43_fu_221_p2 & and_ln43_fu_229_p2);

assign and_ln43_fu_229_p2 = (or_ln43_1_fu_225_p2 & grp_fu_86_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign grp_fu_86_p0 = y_q1;

assign grp_fu_86_p1 = y_q0;

assign icmp_ln43_1_fu_192_p2 = ((trunc_ln43_fu_168_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln43_2_fu_198_p2 = ((tmp_2_fu_172_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln43_3_fu_204_p2 = ((trunc_ln43_1_fu_182_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln43_fu_186_p2 = ((tmp_1_fu_158_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln5658_fu_111_p2 = ((idx_fu_46 == 3'd4) ? 1'b1 : 1'b0);

assign lshr_ln_fu_128_p4 = {{p_result_1_fu_50[5:3]}};

assign or_ln43_1_fu_225_p2 = (icmp_ln43_3_reg_315 | icmp_ln43_2_reg_310);

assign or_ln43_fu_221_p2 = (icmp_ln43_reg_300 | icmp_ln43_1_reg_305);

assign p_first_assign_fu_210_p3 = {{add_ln5658_reg_275}, {3'd0}};

assign p_result_1_out = p_result_1_fu_50[34:0];

assign p_result_fu_241_p3 = ((and_ln43_1_fu_235_p2[0:0] == 1'b1) ? zext_ln5653_fu_217_p1 : p_result_2_reg_267);

assign tmp_1_fu_158_p4 = {{y_q1[62:52]}};

assign tmp_2_fu_172_p4 = {{y_q0[62:52]}};

assign trunc_ln43_1_fu_182_p1 = y_q0[51:0];

assign trunc_ln43_fu_168_p1 = y_q1[51:0];

assign y_address0 = zext_ln5658_fu_123_p1;

assign y_address1 = zext_ln43_fu_138_p1;

assign y_ce0 = y_ce0_local;

assign y_ce1 = y_ce1_local;

assign zext_ln43_fu_138_p1 = lshr_ln_fu_128_p4;

assign zext_ln5653_fu_217_p1 = p_first_assign_fu_210_p3;

assign zext_ln5658_fu_123_p1 = add_ln5658_fu_117_p2;

endmodule //predict_model_predict_model_Pipeline_3
