// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="predict_model_predict_model,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcau20p-sfvb784-2-i,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.835000,HLS_SYN_LAT=248,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=10965,HLS_SYN_LUT=9140,HLS_VERSION=2025_1}" *)

module predict_model (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x,
        ap_return
);

parameter    ap_ST_fsm_state1 = 117'd1;
parameter    ap_ST_fsm_state2 = 117'd2;
parameter    ap_ST_fsm_state3 = 117'd4;
parameter    ap_ST_fsm_state4 = 117'd8;
parameter    ap_ST_fsm_state5 = 117'd16;
parameter    ap_ST_fsm_state6 = 117'd32;
parameter    ap_ST_fsm_state7 = 117'd64;
parameter    ap_ST_fsm_state8 = 117'd128;
parameter    ap_ST_fsm_state9 = 117'd256;
parameter    ap_ST_fsm_state10 = 117'd512;
parameter    ap_ST_fsm_state11 = 117'd1024;
parameter    ap_ST_fsm_state12 = 117'd2048;
parameter    ap_ST_fsm_state13 = 117'd4096;
parameter    ap_ST_fsm_state14 = 117'd8192;
parameter    ap_ST_fsm_state15 = 117'd16384;
parameter    ap_ST_fsm_state16 = 117'd32768;
parameter    ap_ST_fsm_state17 = 117'd65536;
parameter    ap_ST_fsm_state18 = 117'd131072;
parameter    ap_ST_fsm_state19 = 117'd262144;
parameter    ap_ST_fsm_state20 = 117'd524288;
parameter    ap_ST_fsm_state21 = 117'd1048576;
parameter    ap_ST_fsm_state22 = 117'd2097152;
parameter    ap_ST_fsm_state23 = 117'd4194304;
parameter    ap_ST_fsm_state24 = 117'd8388608;
parameter    ap_ST_fsm_state25 = 117'd16777216;
parameter    ap_ST_fsm_state26 = 117'd33554432;
parameter    ap_ST_fsm_state27 = 117'd67108864;
parameter    ap_ST_fsm_state28 = 117'd134217728;
parameter    ap_ST_fsm_state29 = 117'd268435456;
parameter    ap_ST_fsm_state30 = 117'd536870912;
parameter    ap_ST_fsm_state31 = 117'd1073741824;
parameter    ap_ST_fsm_state32 = 117'd2147483648;
parameter    ap_ST_fsm_state33 = 117'd4294967296;
parameter    ap_ST_fsm_state34 = 117'd8589934592;
parameter    ap_ST_fsm_state35 = 117'd17179869184;
parameter    ap_ST_fsm_state36 = 117'd34359738368;
parameter    ap_ST_fsm_state37 = 117'd68719476736;
parameter    ap_ST_fsm_state38 = 117'd137438953472;
parameter    ap_ST_fsm_state39 = 117'd274877906944;
parameter    ap_ST_fsm_state40 = 117'd549755813888;
parameter    ap_ST_fsm_state41 = 117'd1099511627776;
parameter    ap_ST_fsm_state42 = 117'd2199023255552;
parameter    ap_ST_fsm_state43 = 117'd4398046511104;
parameter    ap_ST_fsm_state44 = 117'd8796093022208;
parameter    ap_ST_fsm_state45 = 117'd17592186044416;
parameter    ap_ST_fsm_state46 = 117'd35184372088832;
parameter    ap_ST_fsm_state47 = 117'd70368744177664;
parameter    ap_ST_fsm_state48 = 117'd140737488355328;
parameter    ap_ST_fsm_state49 = 117'd281474976710656;
parameter    ap_ST_fsm_state50 = 117'd562949953421312;
parameter    ap_ST_fsm_state51 = 117'd1125899906842624;
parameter    ap_ST_fsm_state52 = 117'd2251799813685248;
parameter    ap_ST_fsm_state53 = 117'd4503599627370496;
parameter    ap_ST_fsm_state54 = 117'd9007199254740992;
parameter    ap_ST_fsm_state55 = 117'd18014398509481984;
parameter    ap_ST_fsm_state56 = 117'd36028797018963968;
parameter    ap_ST_fsm_state57 = 117'd72057594037927936;
parameter    ap_ST_fsm_state58 = 117'd144115188075855872;
parameter    ap_ST_fsm_state59 = 117'd288230376151711744;
parameter    ap_ST_fsm_state60 = 117'd576460752303423488;
parameter    ap_ST_fsm_state61 = 117'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 117'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 117'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 117'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 117'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 117'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 117'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 117'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 117'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 117'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 117'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 117'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 117'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 117'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 117'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 117'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 117'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 117'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 117'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 117'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 117'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 117'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 117'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 117'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 117'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 117'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 117'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 117'd154742504910672534362390528;
parameter    ap_ST_fsm_state89 = 117'd309485009821345068724781056;
parameter    ap_ST_fsm_state90 = 117'd618970019642690137449562112;
parameter    ap_ST_fsm_state91 = 117'd1237940039285380274899124224;
parameter    ap_ST_fsm_state92 = 117'd2475880078570760549798248448;
parameter    ap_ST_fsm_state93 = 117'd4951760157141521099596496896;
parameter    ap_ST_fsm_state94 = 117'd9903520314283042199192993792;
parameter    ap_ST_fsm_state95 = 117'd19807040628566084398385987584;
parameter    ap_ST_fsm_state96 = 117'd39614081257132168796771975168;
parameter    ap_ST_fsm_state97 = 117'd79228162514264337593543950336;
parameter    ap_ST_fsm_state98 = 117'd158456325028528675187087900672;
parameter    ap_ST_fsm_state99 = 117'd316912650057057350374175801344;
parameter    ap_ST_fsm_state100 = 117'd633825300114114700748351602688;
parameter    ap_ST_fsm_state101 = 117'd1267650600228229401496703205376;
parameter    ap_ST_fsm_state102 = 117'd2535301200456458802993406410752;
parameter    ap_ST_fsm_state103 = 117'd5070602400912917605986812821504;
parameter    ap_ST_fsm_state104 = 117'd10141204801825835211973625643008;
parameter    ap_ST_fsm_state105 = 117'd20282409603651670423947251286016;
parameter    ap_ST_fsm_state106 = 117'd40564819207303340847894502572032;
parameter    ap_ST_fsm_state107 = 117'd81129638414606681695789005144064;
parameter    ap_ST_fsm_state108 = 117'd162259276829213363391578010288128;
parameter    ap_ST_fsm_state109 = 117'd324518553658426726783156020576256;
parameter    ap_ST_fsm_state110 = 117'd649037107316853453566312041152512;
parameter    ap_ST_fsm_state111 = 117'd1298074214633706907132624082305024;
parameter    ap_ST_fsm_state112 = 117'd2596148429267413814265248164610048;
parameter    ap_ST_fsm_state113 = 117'd5192296858534827628530496329220096;
parameter    ap_ST_fsm_state114 = 117'd10384593717069655257060992658440192;
parameter    ap_ST_fsm_state115 = 117'd20769187434139310514121985316880384;
parameter    ap_ST_fsm_state116 = 117'd41538374868278621028243970633760768;
parameter    ap_ST_fsm_state117 = 117'd83076749736557242056487941267521536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [191:0] x;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [116:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] grp_fu_192_p2;
reg   [63:0] reg_231;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state28;
wire   [63:0] grp_fu_197_p2;
reg   [63:0] reg_237;
wire   [63:0] grp_fu_202_p2;
reg   [63:0] reg_243;
wire    ap_CS_fsm_state29;
reg   [63:0] reg_249;
wire    ap_CS_fsm_state16;
reg   [63:0] reg_255;
wire   [63:0] grp_fu_174_p2;
reg   [63:0] reg_261;
wire    ap_CS_fsm_state41;
wire    ap_CS_fsm_state54;
wire    ap_CS_fsm_state55;
wire    ap_CS_fsm_state56;
wire    ap_CS_fsm_state74;
wire    ap_CS_fsm_state87;
wire    ap_CS_fsm_state100;
wire    ap_CS_fsm_state113;
wire   [63:0] grp_fu_178_p2;
reg   [63:0] reg_267;
reg   [63:0] reg_272;
wire    ap_CS_fsm_state42;
reg   [63:0] reg_277;
wire   [63:0] grp_fu_182_p2;
reg   [63:0] reg_282;
reg   [63:0] reg_288;
wire    ap_CS_fsm_state61;
wire   [63:0] bitcast_ln28_fu_297_p1;
reg   [63:0] bitcast_ln28_reg_408;
wire   [63:0] bitcast_ln28_1_fu_313_p1;
reg   [63:0] bitcast_ln28_1_reg_415;
reg   [63:0] trunc_ln28_2_reg_422;
wire   [63:0] bitcast_ln28_2_fu_329_p1;
reg   [63:0] bitcast_ln28_2_reg_427;
wire    ap_CS_fsm_state14;
wire   [63:0] grp_fu_207_p2;
reg   [63:0] mul2_reg_434;
reg   [63:0] mul8_reg_439;
reg   [63:0] mul10_reg_444;
wire   [63:0] grp_fu_216_p2;
reg   [63:0] mul12_reg_449;
wire   [63:0] grp_fu_221_p2;
reg   [63:0] mul13_reg_454;
wire   [2:0] y_addr_2_reg_469;
wire   [2:0] y_addr_3_reg_474;
wire    ap_CS_fsm_state57;
reg   [63:0] y_load_1_reg_484;
wire   [63:0] bitcast_ln41_fu_359_p1;
wire    ap_CS_fsm_state62;
wire   [63:0] bitcast_ln41_1_fu_364_p1;
wire   [63:0] bitcast_ln41_2_fu_368_p1;
wire    ap_CS_fsm_state75;
wire   [63:0] bitcast_ln41_3_fu_373_p1;
wire    ap_CS_fsm_state88;
wire   [63:0] bitcast_ln41_4_fu_378_p1;
wire    ap_CS_fsm_state101;
reg   [2:0] y_address0;
reg    y_ce0;
reg    y_we0;
reg   [63:0] y_d0;
wire   [63:0] y_q0;
reg   [2:0] y_address1;
reg    y_ce1;
wire   [63:0] y_q1;
wire    grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_ap_start;
wire    grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_ap_done;
wire    grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_ap_idle;
wire    grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_ap_ready;
wire   [2:0] grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_y_address0;
wire    grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_y_ce0;
wire    grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_y_we0;
wire   [63:0] grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_y_d0;
wire   [2:0] grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_y_address1;
wire    grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_y_ce1;
wire    grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_ap_start;
wire    grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_ap_done;
wire    grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_ap_idle;
wire    grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_ap_ready;
wire   [2:0] grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_y_address0;
wire    grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_y_ce0;
wire    grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_y_we0;
wire   [63:0] grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_y_d0;
wire   [2:0] grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_y_address1;
wire    grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_y_ce1;
wire    grp_predict_model_Pipeline_3_fu_168_ap_start;
wire    grp_predict_model_Pipeline_3_fu_168_ap_done;
wire    grp_predict_model_Pipeline_3_fu_168_ap_idle;
wire    grp_predict_model_Pipeline_3_fu_168_ap_ready;
wire   [2:0] grp_predict_model_Pipeline_3_fu_168_y_address0;
wire    grp_predict_model_Pipeline_3_fu_168_y_ce0;
wire   [2:0] grp_predict_model_Pipeline_3_fu_168_y_address1;
wire    grp_predict_model_Pipeline_3_fu_168_y_ce1;
wire   [34:0] grp_predict_model_Pipeline_3_fu_168_p_result_1_out;
wire    grp_predict_model_Pipeline_3_fu_168_p_result_1_out_ap_vld;
reg    grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_ap_start_reg;
wire    ap_CS_fsm_state58;
wire    ap_CS_fsm_state59;
wire    y_we0_out;
reg    grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_ap_start_reg;
wire    ap_CS_fsm_state114;
reg    grp_predict_model_Pipeline_3_fu_168_ap_start_reg;
reg   [116:0] ap_NS_fsm;
wire    ap_NS_fsm_state115;
wire    ap_CS_fsm_state116;
reg   [34:0] p_result_1_loc_fu_94;
wire    ap_CS_fsm_state117;
reg    y_we1_local;
reg   [63:0] y_d1_local;
wire   [63:0] bitcast_ln28_3_fu_334_p1;
reg    y_ce1_local;
reg   [2:0] y_address1_local;
reg    y_we0_local;
reg   [63:0] y_d0_local;
wire   [63:0] bitcast_ln29_fu_339_p1;
reg    y_ce0_local;
reg   [2:0] y_address0_local;
wire   [63:0] bitcast_ln30_fu_344_p1;
wire   [63:0] bitcast_ln31_fu_349_p1;
wire   [63:0] bitcast_ln32_fu_354_p1;
wire    ap_CS_fsm_state60;
wire    ap_CS_fsm_state73;
wire    ap_CS_fsm_state86;
wire    ap_CS_fsm_state99;
reg   [63:0] grp_fu_174_p0;
reg   [63:0] grp_fu_174_p1;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state43;
wire    ap_CS_fsm_state44;
reg   [63:0] grp_fu_178_p0;
reg   [63:0] grp_fu_178_p1;
reg   [63:0] grp_fu_182_p0;
reg   [63:0] grp_fu_182_p1;
reg   [63:0] grp_fu_192_p0;
reg   [63:0] grp_fu_192_p1;
wire    ap_CS_fsm_state2;
reg   [63:0] grp_fu_197_p0;
reg   [63:0] grp_fu_197_p1;
reg   [63:0] grp_fu_202_p0;
reg   [63:0] grp_fu_202_p1;
reg   [63:0] grp_fu_207_p0;
reg   [63:0] grp_fu_207_p1;
wire   [63:0] trunc_ln28_fu_293_p1;
wire   [63:0] trunc_ln28_1_fu_303_p4;
wire   [31:0] trunc_ln1_fu_386_p4;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
reg    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
wire    ap_ST_fsm_state74_blk;
wire    ap_ST_fsm_state75_blk;
wire    ap_ST_fsm_state76_blk;
wire    ap_ST_fsm_state77_blk;
wire    ap_ST_fsm_state78_blk;
wire    ap_ST_fsm_state79_blk;
wire    ap_ST_fsm_state80_blk;
wire    ap_ST_fsm_state81_blk;
wire    ap_ST_fsm_state82_blk;
wire    ap_ST_fsm_state83_blk;
wire    ap_ST_fsm_state84_blk;
wire    ap_ST_fsm_state85_blk;
wire    ap_ST_fsm_state86_blk;
wire    ap_ST_fsm_state87_blk;
wire    ap_ST_fsm_state88_blk;
wire    ap_ST_fsm_state89_blk;
wire    ap_ST_fsm_state90_blk;
wire    ap_ST_fsm_state91_blk;
wire    ap_ST_fsm_state92_blk;
wire    ap_ST_fsm_state93_blk;
wire    ap_ST_fsm_state94_blk;
wire    ap_ST_fsm_state95_blk;
wire    ap_ST_fsm_state96_blk;
wire    ap_ST_fsm_state97_blk;
wire    ap_ST_fsm_state98_blk;
wire    ap_ST_fsm_state99_blk;
wire    ap_ST_fsm_state100_blk;
wire    ap_ST_fsm_state101_blk;
wire    ap_ST_fsm_state102_blk;
wire    ap_ST_fsm_state103_blk;
wire    ap_ST_fsm_state104_blk;
wire    ap_ST_fsm_state105_blk;
wire    ap_ST_fsm_state106_blk;
wire    ap_ST_fsm_state107_blk;
wire    ap_ST_fsm_state108_blk;
wire    ap_ST_fsm_state109_blk;
wire    ap_ST_fsm_state110_blk;
wire    ap_ST_fsm_state111_blk;
wire    ap_ST_fsm_state112_blk;
wire    ap_ST_fsm_state113_blk;
reg    ap_ST_fsm_state114_blk;
wire    ap_ST_fsm_state115_blk;
reg    ap_ST_fsm_state116_blk;
wire    ap_ST_fsm_state117_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 117'd1;
#0 grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_ap_start_reg = 1'b0;
#0 grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_ap_start_reg = 1'b0;
#0 grp_predict_model_Pipeline_3_fu_168_ap_start_reg = 1'b0;
end

predict_model_y_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
y_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(y_address0),
    .ce0(y_ce0),
    .we0(y_we0),
    .d0(y_d0),
    .q0(y_q0),
    .address1(y_address1),
    .ce1(y_ce1),
    .we1(y_we1_local),
    .d1(y_d1_local),
    .q1(y_q1)
);

predict_model_predict_model_Pipeline_VITIS_LOOP_35_1 grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_ap_start),
    .ap_done(grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_ap_done),
    .ap_idle(grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_ap_idle),
    .ap_ready(grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_ap_ready),
    .y_address0(grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_y_address0),
    .y_ce0(grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_y_ce0),
    .y_we0(grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_y_we0),
    .y_d0(grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_y_d0),
    .y_address1(grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_y_address1),
    .y_ce1(grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_y_ce1),
    .y_q1(y_q1)
);

predict_model_predict_model_Pipeline_VITIS_LOOP_44_2 grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_ap_start),
    .ap_done(grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_ap_done),
    .ap_idle(grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_ap_idle),
    .ap_ready(grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_ap_ready),
    .y_address0(grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_y_address0),
    .y_ce0(grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_y_ce0),
    .y_we0(grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_y_we0),
    .y_d0(grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_y_d0),
    .y_address1(grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_y_address1),
    .y_ce1(grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_y_ce1),
    .y_q1(y_q1),
    .Z(reg_261)
);

predict_model_predict_model_Pipeline_3 grp_predict_model_Pipeline_3_fu_168(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_predict_model_Pipeline_3_fu_168_ap_start),
    .ap_done(grp_predict_model_Pipeline_3_fu_168_ap_done),
    .ap_idle(grp_predict_model_Pipeline_3_fu_168_ap_idle),
    .ap_ready(grp_predict_model_Pipeline_3_fu_168_ap_ready),
    .y_address0(grp_predict_model_Pipeline_3_fu_168_y_address0),
    .y_ce0(grp_predict_model_Pipeline_3_fu_168_y_ce0),
    .y_q0(y_q0),
    .y_address1(grp_predict_model_Pipeline_3_fu_168_y_address1),
    .y_ce1(grp_predict_model_Pipeline_3_fu_168_y_ce1),
    .y_q1(y_q1),
    .p_result_1_out(grp_predict_model_Pipeline_3_fu_168_p_result_1_out),
    .p_result_1_out_ap_vld(grp_predict_model_Pipeline_3_fu_168_p_result_1_out_ap_vld)
);

predict_model_dadd_64ns_64ns_64_13_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_13_full_dsp_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_174_p0),
    .din1(grp_fu_174_p1),
    .ce(1'b1),
    .dout(grp_fu_174_p2)
);

predict_model_dadd_64ns_64ns_64_13_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_13_full_dsp_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_178_p0),
    .din1(grp_fu_178_p1),
    .ce(1'b1),
    .dout(grp_fu_178_p2)
);

predict_model_dadd_64ns_64ns_64_13_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_13_full_dsp_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_182_p0),
    .din1(grp_fu_182_p1),
    .ce(1'b1),
    .dout(grp_fu_182_p2)
);

predict_model_dmul_64ns_64ns_64_15_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 15 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_15_max_dsp_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_192_p0),
    .din1(grp_fu_192_p1),
    .ce(1'b1),
    .dout(grp_fu_192_p2)
);

predict_model_dmul_64ns_64ns_64_15_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 15 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_15_max_dsp_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_197_p0),
    .din1(grp_fu_197_p1),
    .ce(1'b1),
    .dout(grp_fu_197_p2)
);

predict_model_dmul_64ns_64ns_64_15_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 15 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_15_max_dsp_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_202_p0),
    .din1(grp_fu_202_p1),
    .ce(1'b1),
    .dout(grp_fu_202_p2)
);

predict_model_dmul_64ns_64ns_64_15_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 15 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_15_max_dsp_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_207_p0),
    .din1(grp_fu_207_p1),
    .ce(1'b1),
    .dout(grp_fu_207_p2)
);

predict_model_dmul_64ns_64ns_64_15_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 15 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_15_max_dsp_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln28_reg_408),
    .din1(64'd13818919879075586399),
    .ce(1'b1),
    .dout(grp_fu_216_p2)
);

predict_model_dmul_64ns_64ns_64_15_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 15 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_15_max_dsp_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bitcast_ln28_1_reg_415),
    .din1(64'd13812636405354299345),
    .ce(1'b1),
    .dout(grp_fu_221_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_predict_model_Pipeline_3_fu_168_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state115) & (1'b1 == ap_CS_fsm_state114))) begin
            grp_predict_model_Pipeline_3_fu_168_ap_start_reg <= 1'b1;
        end else if ((grp_predict_model_Pipeline_3_fu_168_ap_ready == 1'b1)) begin
            grp_predict_model_Pipeline_3_fu_168_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state58)) begin
            grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_ap_start_reg <= 1'b1;
        end else if ((grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_ap_ready == 1'b1)) begin
            grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state113)) begin
            grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_ap_start_reg <= 1'b1;
        end else if ((grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_ap_ready == 1'b1)) begin
            grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state100) | (1'b1 == ap_CS_fsm_state74))) begin
        reg_288 <= y_q1;
    end else if (((1'b1 == ap_CS_fsm_state61) | (1'b1 == ap_CS_fsm_state87))) begin
        reg_288 <= y_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        bitcast_ln28_1_reg_415 <= bitcast_ln28_1_fu_313_p1;
        bitcast_ln28_reg_408 <= bitcast_ln28_fu_297_p1;
        trunc_ln28_2_reg_422 <= {{x[191:128]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        bitcast_ln28_2_reg_427 <= bitcast_ln28_2_fu_329_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        mul10_reg_444 <= grp_fu_207_p2;
        mul12_reg_449 <= grp_fu_216_p2;
        mul13_reg_454 <= grp_fu_221_p2;
        mul8_reg_439 <= grp_fu_202_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        mul2_reg_434 <= grp_fu_207_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_predict_model_Pipeline_3_fu_168_p_result_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state116))) begin
        p_result_1_loc_fu_94 <= grp_predict_model_Pipeline_3_fu_168_p_result_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state15))) begin
        reg_231 <= grp_fu_192_p2;
        reg_237 <= grp_fu_197_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state15))) begin
        reg_243 <= grp_fu_202_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state29))) begin
        reg_249 <= grp_fu_192_p2;
        reg_255 <= grp_fu_197_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state113) | (1'b1 == ap_CS_fsm_state100) | (1'b1 == ap_CS_fsm_state87) | (1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state28))) begin
        reg_261 <= grp_fu_174_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state28))) begin
        reg_267 <= grp_fu_178_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state29))) begin
        reg_272 <= grp_fu_174_p2;
        reg_277 <= grp_fu_178_p2;
        reg_282 <= grp_fu_182_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state61)) begin
        y_load_1_reg_484 <= y_q1;
    end
end

assign ap_ST_fsm_state100_blk = 1'b0;

assign ap_ST_fsm_state101_blk = 1'b0;

assign ap_ST_fsm_state102_blk = 1'b0;

assign ap_ST_fsm_state103_blk = 1'b0;

assign ap_ST_fsm_state104_blk = 1'b0;

assign ap_ST_fsm_state105_blk = 1'b0;

assign ap_ST_fsm_state106_blk = 1'b0;

assign ap_ST_fsm_state107_blk = 1'b0;

assign ap_ST_fsm_state108_blk = 1'b0;

assign ap_ST_fsm_state109_blk = 1'b0;

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state110_blk = 1'b0;

assign ap_ST_fsm_state111_blk = 1'b0;

assign ap_ST_fsm_state112_blk = 1'b0;

assign ap_ST_fsm_state113_blk = 1'b0;

always @ (*) begin
    if ((grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_ap_done == 1'b0)) begin
        ap_ST_fsm_state114_blk = 1'b1;
    end else begin
        ap_ST_fsm_state114_blk = 1'b0;
    end
end

assign ap_ST_fsm_state115_blk = 1'b0;

always @ (*) begin
    if ((grp_predict_model_Pipeline_3_fu_168_ap_done == 1'b0)) begin
        ap_ST_fsm_state116_blk = 1'b1;
    end else begin
        ap_ST_fsm_state116_blk = 1'b0;
    end
end

assign ap_ST_fsm_state117_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

always @ (*) begin
    if ((grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_ap_done == 1'b0)) begin
        ap_ST_fsm_state59_blk = 1'b1;
    end else begin
        ap_ST_fsm_state59_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

assign ap_ST_fsm_state74_blk = 1'b0;

assign ap_ST_fsm_state75_blk = 1'b0;

assign ap_ST_fsm_state76_blk = 1'b0;

assign ap_ST_fsm_state77_blk = 1'b0;

assign ap_ST_fsm_state78_blk = 1'b0;

assign ap_ST_fsm_state79_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state80_blk = 1'b0;

assign ap_ST_fsm_state81_blk = 1'b0;

assign ap_ST_fsm_state82_blk = 1'b0;

assign ap_ST_fsm_state83_blk = 1'b0;

assign ap_ST_fsm_state84_blk = 1'b0;

assign ap_ST_fsm_state85_blk = 1'b0;

assign ap_ST_fsm_state86_blk = 1'b0;

assign ap_ST_fsm_state87_blk = 1'b0;

assign ap_ST_fsm_state88_blk = 1'b0;

assign ap_ST_fsm_state89_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state90_blk = 1'b0;

assign ap_ST_fsm_state91_blk = 1'b0;

assign ap_ST_fsm_state92_blk = 1'b0;

assign ap_ST_fsm_state93_blk = 1'b0;

assign ap_ST_fsm_state94_blk = 1'b0;

assign ap_ST_fsm_state95_blk = 1'b0;

assign ap_ST_fsm_state96_blk = 1'b0;

assign ap_ST_fsm_state97_blk = 1'b0;

assign ap_ST_fsm_state98_blk = 1'b0;

assign ap_ST_fsm_state99_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state117)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state117)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state62)) begin
        grp_fu_174_p0 = bitcast_ln41_fu_359_p1;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        grp_fu_174_p0 = reg_282;
    end else if (((1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state30))) begin
        grp_fu_174_p0 = reg_272;
    end else if (((1'b1 == ap_CS_fsm_state101) | (1'b1 == ap_CS_fsm_state88) | (1'b1 == ap_CS_fsm_state75) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_174_p0 = reg_261;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_174_p0 = reg_249;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_174_p0 = reg_231;
    end else begin
        grp_fu_174_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state101)) begin
        grp_fu_174_p1 = bitcast_ln41_4_fu_378_p1;
    end else if ((1'b1 == ap_CS_fsm_state88)) begin
        grp_fu_174_p1 = bitcast_ln41_3_fu_373_p1;
    end else if ((1'b1 == ap_CS_fsm_state75)) begin
        grp_fu_174_p1 = bitcast_ln41_2_fu_368_p1;
    end else if ((1'b1 == ap_CS_fsm_state62)) begin
        grp_fu_174_p1 = bitcast_ln41_1_fu_364_p1;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        grp_fu_174_p1 = 64'd4627660233233564195;
    end else if ((1'b1 == ap_CS_fsm_state43)) begin
        grp_fu_174_p1 = 64'd4627441646963965854;
    end else if ((1'b1 == ap_CS_fsm_state42)) begin
        grp_fu_174_p1 = 64'd13859357513784163563;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_174_p1 = reg_249;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        grp_fu_174_p1 = reg_231;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_174_p1 = reg_255;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_174_p1 = reg_237;
    end else begin
        grp_fu_174_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state30))) begin
        grp_fu_178_p0 = reg_277;
    end else if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_178_p0 = reg_267;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_178_p0 = mul8_reg_439;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_178_p0 = reg_243;
    end else begin
        grp_fu_178_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        grp_fu_178_p1 = 64'd4626699342827345873;
    end else if ((1'b1 == ap_CS_fsm_state42)) begin
        grp_fu_178_p1 = 64'd4626111887676525880;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_178_p1 = reg_255;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        grp_fu_178_p1 = reg_237;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_178_p1 = mul10_reg_444;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_178_p1 = mul2_reg_434;
    end else begin
        grp_fu_178_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_182_p0 = reg_282;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_182_p0 = mul12_reg_449;
    end else begin
        grp_fu_182_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_182_p1 = reg_243;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_182_p1 = mul13_reg_454;
    end else begin
        grp_fu_182_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_192_p0 = bitcast_ln28_2_reg_427;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_192_p0 = bitcast_ln28_2_fu_329_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_192_p0 = bitcast_ln28_reg_408;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_192_p0 = bitcast_ln28_fu_297_p1;
    end else begin
        grp_fu_192_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_192_p1 = 64'd13804289404981893253;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_192_p1 = 64'd4590420153572917452;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_192_p1 = 64'd4590996072452113710;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_192_p1 = 64'd4587508473371462952;
    end else begin
        grp_fu_192_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_197_p0 = bitcast_ln28_2_reg_427;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_197_p0 = bitcast_ln28_2_fu_329_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_197_p0 = bitcast_ln28_1_reg_415;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_197_p0 = bitcast_ln28_1_fu_313_p1;
    end else begin
        grp_fu_197_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_197_p1 = 64'd13807208786698998527;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_197_p1 = 64'd13799612561604633009;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_197_p1 = 64'd13817576726963871303;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_197_p1 = 64'd4600722601771433066;
    end else begin
        grp_fu_197_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_202_p0 = bitcast_ln28_2_reg_427;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_202_p0 = bitcast_ln28_reg_408;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_202_p0 = bitcast_ln28_fu_297_p1;
    end else begin
        grp_fu_202_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_202_p1 = 64'd13806069060381011905;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_202_p1 = 64'd13818821388954615508;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_202_p1 = 64'd4596826435412011316;
    end else begin
        grp_fu_202_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_207_p0 = bitcast_ln28_1_reg_415;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_207_p0 = bitcast_ln28_1_fu_313_p1;
    end else begin
        grp_fu_207_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_207_p1 = 64'd13804163036138077058;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_207_p1 = 64'd13818663655241554454;
    end else begin
        grp_fu_207_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state116)) begin
        y_address0 = grp_predict_model_Pipeline_3_fu_168_y_address0;
    end else if ((1'b1 == ap_CS_fsm_state114)) begin
        y_address0 = grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_y_address0;
    end else if ((1'b1 == ap_CS_fsm_state59)) begin
        y_address0 = grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_y_address0;
    end else begin
        y_address0 = y_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state86)) begin
        y_address0_local = y_addr_3_reg_474;
    end else if ((1'b1 == ap_CS_fsm_state60)) begin
        y_address0_local = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        y_address0_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state56)) begin
        y_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state55)) begin
        y_address0_local = 64'd1;
    end else begin
        y_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state116)) begin
        y_address1 = grp_predict_model_Pipeline_3_fu_168_y_address1;
    end else if ((1'b1 == ap_CS_fsm_state114)) begin
        y_address1 = grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_y_address1;
    end else if ((1'b1 == ap_CS_fsm_state59)) begin
        y_address1 = grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_y_address1;
    end else begin
        y_address1 = y_address1_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state99)) begin
        y_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state73)) begin
        y_address1_local = y_addr_2_reg_469;
    end else if ((1'b1 == ap_CS_fsm_state60)) begin
        y_address1_local = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state56)) begin
        y_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state55)) begin
        y_address1_local = 64'd0;
    end else begin
        y_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state116)) begin
        y_ce0 = grp_predict_model_Pipeline_3_fu_168_y_ce0;
    end else if ((1'b1 == ap_CS_fsm_state114)) begin
        y_ce0 = grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_y_ce0;
    end else if ((1'b1 == ap_CS_fsm_state59)) begin
        y_ce0 = grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_y_ce0;
    end else begin
        y_ce0 = y_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state86) | (1'b1 == ap_CS_fsm_state60) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state55))) begin
        y_ce0_local = 1'b1;
    end else begin
        y_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state116)) begin
        y_ce1 = grp_predict_model_Pipeline_3_fu_168_y_ce1;
    end else if ((1'b1 == ap_CS_fsm_state114)) begin
        y_ce1 = grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_y_ce1;
    end else if ((1'b1 == ap_CS_fsm_state59)) begin
        y_ce1 = grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_y_ce1;
    end else begin
        y_ce1 = y_ce1_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state99) | (1'b1 == ap_CS_fsm_state73) | (1'b1 == ap_CS_fsm_state60) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state55))) begin
        y_ce1_local = 1'b1;
    end else begin
        y_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state114)) begin
        y_d0 = grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_y_d0;
    end else if ((1'b1 == ap_CS_fsm_state59)) begin
        y_d0 = grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_y_d0;
    end else begin
        y_d0 = y_d0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        y_d0_local = bitcast_ln32_fu_354_p1;
    end else if ((1'b1 == ap_CS_fsm_state56)) begin
        y_d0_local = bitcast_ln31_fu_349_p1;
    end else if ((1'b1 == ap_CS_fsm_state55)) begin
        y_d0_local = bitcast_ln29_fu_339_p1;
    end else begin
        y_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        y_d1_local = bitcast_ln30_fu_344_p1;
    end else if ((1'b1 == ap_CS_fsm_state55)) begin
        y_d1_local = bitcast_ln28_3_fu_334_p1;
    end else begin
        y_d1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state114)) begin
        y_we0 = grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_y_we0;
    end else if ((1'b1 == ap_CS_fsm_state59)) begin
        y_we0 = grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_y_we0;
    end else begin
        y_we0 = (y_we0_out | 1'b0);
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state55))) begin
        y_we0_local = 1'b1;
    end else begin
        y_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state55))) begin
        y_we1_local = 1'b1;
    end else begin
        y_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            if (((grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state59))) begin
                ap_NS_fsm = ap_ST_fsm_state60;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state59;
            end
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            ap_NS_fsm = ap_ST_fsm_state89;
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state90;
        end
        ap_ST_fsm_state90 : begin
            ap_NS_fsm = ap_ST_fsm_state91;
        end
        ap_ST_fsm_state91 : begin
            ap_NS_fsm = ap_ST_fsm_state92;
        end
        ap_ST_fsm_state92 : begin
            ap_NS_fsm = ap_ST_fsm_state93;
        end
        ap_ST_fsm_state93 : begin
            ap_NS_fsm = ap_ST_fsm_state94;
        end
        ap_ST_fsm_state94 : begin
            ap_NS_fsm = ap_ST_fsm_state95;
        end
        ap_ST_fsm_state95 : begin
            ap_NS_fsm = ap_ST_fsm_state96;
        end
        ap_ST_fsm_state96 : begin
            ap_NS_fsm = ap_ST_fsm_state97;
        end
        ap_ST_fsm_state97 : begin
            ap_NS_fsm = ap_ST_fsm_state98;
        end
        ap_ST_fsm_state98 : begin
            ap_NS_fsm = ap_ST_fsm_state99;
        end
        ap_ST_fsm_state99 : begin
            ap_NS_fsm = ap_ST_fsm_state100;
        end
        ap_ST_fsm_state100 : begin
            ap_NS_fsm = ap_ST_fsm_state101;
        end
        ap_ST_fsm_state101 : begin
            ap_NS_fsm = ap_ST_fsm_state102;
        end
        ap_ST_fsm_state102 : begin
            ap_NS_fsm = ap_ST_fsm_state103;
        end
        ap_ST_fsm_state103 : begin
            ap_NS_fsm = ap_ST_fsm_state104;
        end
        ap_ST_fsm_state104 : begin
            ap_NS_fsm = ap_ST_fsm_state105;
        end
        ap_ST_fsm_state105 : begin
            ap_NS_fsm = ap_ST_fsm_state106;
        end
        ap_ST_fsm_state106 : begin
            ap_NS_fsm = ap_ST_fsm_state107;
        end
        ap_ST_fsm_state107 : begin
            ap_NS_fsm = ap_ST_fsm_state108;
        end
        ap_ST_fsm_state108 : begin
            ap_NS_fsm = ap_ST_fsm_state109;
        end
        ap_ST_fsm_state109 : begin
            ap_NS_fsm = ap_ST_fsm_state110;
        end
        ap_ST_fsm_state110 : begin
            ap_NS_fsm = ap_ST_fsm_state111;
        end
        ap_ST_fsm_state111 : begin
            ap_NS_fsm = ap_ST_fsm_state112;
        end
        ap_ST_fsm_state112 : begin
            ap_NS_fsm = ap_ST_fsm_state113;
        end
        ap_ST_fsm_state113 : begin
            ap_NS_fsm = ap_ST_fsm_state114;
        end
        ap_ST_fsm_state114 : begin
            if (((grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state114))) begin
                ap_NS_fsm = ap_ST_fsm_state115;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state114;
            end
        end
        ap_ST_fsm_state115 : begin
            ap_NS_fsm = ap_ST_fsm_state116;
        end
        ap_ST_fsm_state116 : begin
            if (((grp_predict_model_Pipeline_3_fu_168_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state116))) begin
                ap_NS_fsm = ap_ST_fsm_state117;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state116;
            end
        end
        ap_ST_fsm_state117 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state100 = ap_CS_fsm[32'd99];

assign ap_CS_fsm_state101 = ap_CS_fsm[32'd100];

assign ap_CS_fsm_state113 = ap_CS_fsm[32'd112];

assign ap_CS_fsm_state114 = ap_CS_fsm[32'd113];

assign ap_CS_fsm_state116 = ap_CS_fsm[32'd115];

assign ap_CS_fsm_state117 = ap_CS_fsm[32'd116];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state54 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd58];

assign ap_CS_fsm_state60 = ap_CS_fsm[32'd59];

assign ap_CS_fsm_state61 = ap_CS_fsm[32'd60];

assign ap_CS_fsm_state62 = ap_CS_fsm[32'd61];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

assign ap_CS_fsm_state75 = ap_CS_fsm[32'd74];

assign ap_CS_fsm_state86 = ap_CS_fsm[32'd85];

assign ap_CS_fsm_state87 = ap_CS_fsm[32'd86];

assign ap_CS_fsm_state88 = ap_CS_fsm[32'd87];

assign ap_CS_fsm_state99 = ap_CS_fsm[32'd98];

assign ap_NS_fsm_state115 = ap_NS_fsm[32'd114];

assign ap_return = (trunc_ln1_fu_386_p4 + 32'd1);

assign bitcast_ln28_1_fu_313_p1 = trunc_ln28_1_fu_303_p4;

assign bitcast_ln28_2_fu_329_p1 = trunc_ln28_2_reg_422;

assign bitcast_ln28_3_fu_334_p1 = reg_261;

assign bitcast_ln28_fu_297_p1 = trunc_ln28_fu_293_p1;

assign bitcast_ln29_fu_339_p1 = reg_267;

assign bitcast_ln30_fu_344_p1 = reg_261;

assign bitcast_ln31_fu_349_p1 = reg_267;

assign bitcast_ln32_fu_354_p1 = reg_261;

assign bitcast_ln41_1_fu_364_p1 = y_load_1_reg_484;

assign bitcast_ln41_2_fu_368_p1 = reg_288;

assign bitcast_ln41_3_fu_373_p1 = reg_288;

assign bitcast_ln41_4_fu_378_p1 = reg_288;

assign bitcast_ln41_fu_359_p1 = reg_288;

assign grp_predict_model_Pipeline_3_fu_168_ap_start = grp_predict_model_Pipeline_3_fu_168_ap_start_reg;

assign grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_ap_start = grp_predict_model_Pipeline_VITIS_LOOP_35_1_fu_157_ap_start_reg;

assign grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_ap_start = grp_predict_model_Pipeline_VITIS_LOOP_44_2_fu_162_ap_start_reg;

assign trunc_ln1_fu_386_p4 = {{p_result_1_loc_fu_94[34:3]}};

assign trunc_ln28_1_fu_303_p4 = {{x[127:64]}};

assign trunc_ln28_fu_293_p1 = x[63:0];

assign y_addr_2_reg_469 = 64'd2;

assign y_addr_3_reg_474 = 64'd3;

assign y_we0_out = y_we0_local;

endmodule //predict_model
